# Generated by Django 4.1.1 on 2022-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="SHUESHIA Blog", max_length=50),
        ),
    ]
