# Generated by Django 4.1.1 on 2022-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
