# Generated by Django 4.1.1 on 2022-09-13 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mangaka", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=50)),
                ("publicationdate", models.DateField()),
                ("enddate", models.DateField()),
                ("episodes", models.IntegerField()),
                ("synopsis", models.TextField()),
                ("anime_pic", models.ImageField(upload_to="anime_pics")),
            ],
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mangaka", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=50)),
                ("first_publication", models.DateField()),
                ("chapters", models.IntegerField()),
                ("last_publication", models.DateField()),
                ("synopsis", models.TextField()),
                ("manga_pic", models.ImageField(upload_to="manga_pics")),
            ],
        ),
        migrations.CreateModel(
            name="ReviewManga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_reviews",
                        to="main.manga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewAnime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anime_reviews",
                        to="main.anime",
                    ),
                ),
            ],
        ),
    ]
