# Generated by Django 4.1.1 on 2022-09-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_anime_manga_reviewmanga_reviewanime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewanime",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anime_review",
                to="main.anime",
            ),
        ),
        migrations.AlterField(
            model_name="reviewmanga",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manga_review",
                to="main.manga",
            ),
        ),
    ]
