# Generated by Django 4.1.1 on 2022-09-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_reviewanime_review_alter_reviewmanga_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewanime",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animerevs",
                to="main.anime",
            ),
        ),
        migrations.AlterField(
            model_name="reviewmanga",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mangarevs",
                to="main.manga",
            ),
        ),
    ]
