# Generated by Django 4.1.1 on 2022-09-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_reviewanime_review_alter_reviewmanga_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewanime", old_name="name", new_name="nameR",
        ),
        migrations.RenameField(
            model_name="reviewmanga", old_name="name", new_name="nameR",
        ),
    ]
