# Generated by Django 4.1.1 on 2022-09-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_reviewanime_review_alter_reviewmanga_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewanime", old_name="nameR", new_name="name",
        ),
        migrations.RenameField(
            model_name="reviewmanga", old_name="nameR", new_name="name",
        ),
    ]
